name: marquee_text
description: "Marquee Text is a Flutter widget for smooth, infinitely scrolling
  text, rich content, and custom widgets with flexible controls for direction,
  speed, fading edges, pauses, and animated colors."
version: 1.0.1
homepage: https://github.com/amityamsi/marquee_text
repository: https://github.com/amityamsi/marquee_text
issue_tracker: https://github.com/amityamsi/marquee_text/issues
documentation: https://github.com/amityamsi/marquee_text/wiki
topics:
  - marquee
  - animation
  - text
  - ticker
  - widget

screenshots:
  - description: "Animated demo of the Marquee widget showing smooth scrolling text."
    path: assets/demo.gif

environment:
  flutter: ">=3.0.0"
  sdk: "^3.5.0"

dependencies:
  fading_edge_scrollview: ^4.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

false_secrets:
  - /example/android/.gradle
